name: build-kolla-to-aliyun
on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai


jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT


      - name: Get current date
        id: date
        run: |
          echo "::set-output name=today::$(date +'%Y-%m-%d')"
          echo  $(date)
          ls -al



      - name: Build and Push Docker-AMD64
        run: |
          sudo apt-get update
          sudo apt install -y vim python3 python3-pip gcc g++ htop
          python3 -m pip install kolla
          python3 -m pip install docker
          kolla-build -b ubuntu  -n zhoukunpeng505 -p default -t binary --push 
        #uses: docker/build-push-action@master
        #with:
          #platforms: linux/amd64
          #context: ./${{ steps.vars.outputs.image_name }}
          #push: true
          #tags: registry.cn-hongkong.aliyuncs.com/zhoukunpeng/${{ steps.vars.outputs.image_name }}:${{ steps.date.outputs.today }}-${{ steps.vars.outputs.sha_short }},registry.cn-hongkong.aliyuncs.com/zhoukunpeng/${{ steps.vars.outputs.image_name }}:latest



